### ISSUE TITLE
INPUT can't be taken

### ISSUE THREAD

**Issue by Lohitha3** [paterva/maltego-trx#1]
File "/home/centos/new_project/transforms/GreetPerson.py", line 17, in create_entities
    person_name = request.Value
AttributeError: MaltegoMsg instance has no attribute 'Value'

    .......... this is the error I am getting while executing the transform by placing it on my own server

**Comment by ABWalters** [comment]
Hi,

Can you try printing the dict of the request object to your console using:
```python
print(request.__dict__)
```

Are you starting the python server using `python project.py runserver` ?

[If the MaltegoXML parameter is not passed to the MaltegoMsg constructor correctly, then the value property will not be created.](https://github.com/paterva/maltego-trx/blob/30e8f34a84a67144dce64be219818cd921d8e829/maltego_trx/maltego.py#L214)

**Comment by Lohitha3** [comment]
Hello,
Thankyou for your response.But I have sorted it already.
With regards,
Lohitha
