### ISSUE TITLE
Nested Entities ( I know this has come up before)

### ISSUE THREAD

**Issue by rigred** [paterva/maltego-trx#10]
I'd just like to document this here as well as ask about it again.
https://github.com/paterva/maltego-trx/issues/4
Maltego-TRX and the client itself as of this moment don't support nested entities. 

However I have various specific scenario where this would be incredibly useful to me as developer as well as cost saving to the user.
An API I query can for a given domain return all email addresses and each of those email addresses returns nested within json the specific data associated with that email including names, numbers and the like.

Ideally I'd like my transform to automatically attach this information as new child entities to the corresponding parent.
Which should be possible given how Maltego ingests it's SVG XML data.
- But it's currently not possible to do this cleanly.

The alternatives I've got is:
a) Storing the email data for each email within the email address entity as a dynamic property and then processing this out with another transform or making my transform automatically detect when such property is present. 
Potentially build a machine that runs this one go. 
   - Problems with this approach: lots of checking for existing properties and not overriding other properties
   - Much code duplication for reprocessing attached entity data.

b) Rerunning an email query API call for each email (this costs the user money in terms of total API calls made)

It would be nice to be able to do this in a less hacky way.

**Comment by rigred** [comment]
For others wonder how I have solved this:

- Create a hash of the entity email.
- Create a dynamic property with that hash as name in the entity.
- Store the nested data as serialized object in that dynamic property.
- Set another dynamic attribute called `forcelookup` with `true/false` values ( checkbox support ?)
  - by default `forcelookup` is false and thus the email transform uses the existing data in that dynamic hash property
  - if the user wants to force an api lookup they simply set the value to true.

**Comment by cmlh** [comment]
@phdowling Can this be closed for the same reason as your https://github.com/paterva/maltego-trx/issues/4#issuecomment-579807248 please and transferred to a published roadmap?

**Comment by felixatmaltego** [comment]
To quote @phdowling 
> Closing, as this is not an issue with the maltego-trx library.
