### ISSUE TITLE
Error while executing: 'MaltegoTransform' object has no attribute 'addAdditionalFields'

### ISSUE THREAD

**Issue by SrJok3s** [paterva/maltego-trx#25]
Hello i was trying to add some propierties to one Entity generated by my python3.6 script but i'm getting this error: `'MaltegoTransform' object has no attribute 'addAdditionalFields' `

Any idea? I've tried all

**Comment by crest42** [comment]
Hi,

can you maybe provide more details, like code snippets and parts of the documentation you used?

As far as I can tell there is no such function defined and the only reference I found is in this documentation: https://docs.maltego.com/support/solutions/articles/15000019558-python-local-library-reference#transforms-object--0-0

Please note the disclaimer: Warning: Python Local Library is no longer supported in favor of Python Maltego-TRX.

If you want to add a property in TRX you need to use the addPorperty function. You can find the relevant source code in this file https://github.com/paterva/maltego-trx/blob/7f09a75dd3c699c82730dc740e0cad8a00e672a1/maltego_trx/maltego.py

P. S. it seems like you are calling MaltegoTransform.addAdditionalFields(). You would need to call the function on the Entity object and not the Transform object.

Robin

**Comment by felixatmaltego** [comment]
I'll close this comment as I am pretty sure it is resolved.
