### ISSUE TITLE
Connecting NewEntities with NewEntities

### ISSUE THREAD

**Issue by ytisf** [paterva/maltego-trx#4]
Could not find a way to establish a nested connection. For example, a transform yields a 'Document' entity can be linked to original object. However, it would be **excellent** to be able to correlate another entity to the Document object rather the original request element. 

For example, `Hash --> Document -->DomainInDocument`. Right now it is only possible to connect both the Document object and the Domain to the original Hash object.

**Comment by paul-rchds** [comment]
Unfortunately, you are right, it is not possible to return nested entities from a transform as the Maltego client does not support it. A workaround would be to have two transforms: Hash --> Document and another that does Document -->DomainInDocument

**Comment by ytisf** [comment]
Is this a limitation within Maltego or the TRX library?

**Comment by paul-rchds** [comment]
It is a limitation with Maltego.

**Comment by phdowling** [comment]
To add to this: what you might do in this scenario is to create a second transform that links the "document in document" to the intermediate entity. If you then want to automatically run both Transforms, you can create a Machine in your Maltego client

**Comment by phdowling** [comment]
Closing, as this is not an issue with the maltego-trx library.
