### ISSUE TITLE
UTF8 Characters in response

### ISSUE THREAD

**Issue by UMB-Linus** [paterva/maltego-trx#5]
I have come to notice, that UTF8 Chars, like ÄÖÜ are not correctly sent to Maltego via python TRX.
Here a little test script, it just sends some random "umlaut"

```
from maltego_trx.maltego import UIM_TYPES
from maltego_trx.entities import IPAddress
from maltego_trx.transform import DiscoverableTransform

class testClass(DiscoverableTransform):
    @classmethod
    def create_entities(cls, request, response):
        response.addEntity("maltego.Person", "äüääö")
```

So far I have not been able to find a way to encode the characters correctly.
Any ideas?

**Comment by jmtnz** [comment]
Although this is not a solution, it could be a workaround.

Apparently python and java are calling utf8 to different things.

to fix your particular issue, you should explicitly provide the following encoding at the beginning of your transform

    #!/usr/bin/env python
    # -*- coding: iso-8859-1 -*-

I personally wouldn't consider it solved, but your particular case well might be. Could you confirm?

**Comment by UMB-Linus** [comment]
I just tested in my environment, and yes it actually works!
How I hate encoding issues....

I personally can live like this, but I'd suggest someone put this into the documentation
