### ISSUE TITLE
ERROR: Content is not allowed in prolog 

### ISSUE THREAD

**Issue by jatelohimself** [paterva/maltego-trx#9]
![unnamed](https://user-images.githubusercontent.com/8627188/90789383-88f51880-e30f-11ea-95d4-68351af59a0f.png)

Transform People Search  returned with an error: ParseError at [row,col]:[1,1]
Message: Content is not allowed in prolog (from entity "John Doe")

This happens when I try running local transforms on both Kali Linux and Windows 10, attached are screenshots of the computer specs
![Capture](https://user-images.githubusercontent.com/8627188/90790068-513aa080-e310-11ea-8a94-492412077e47.PNG)

**Comment by jatelohimself** [comment]
project.py local keywordsearchtransform
C:\Users\ddoch\PycharmProjects\maltego-enron\venv\Scripts\python.exe
C:\Users\ddoch\PycharmProjects\maltego-enron
![image](https://user-images.githubusercontent.com/8627188/91056783-1053cc00-e62f-11ea-963d-765ce025011c.png)

**Comment by jatelohimself** [comment]
> @jatelohimself can you please post the command (along with the arguments) you configured in Maltego while setting up these as Local Transforms?

**Comment by cuckool** [comment]
Any updates on this?

**Comment by totakura** [comment]
@cuckool I'm not sure if we can treat this as a bug. What's happening here is that Maltego expects XML to be written by your local transforms. If for some reason you python script writes anything else to the standard output (e.g printing a stack trace upon an exception, logging, or simply print()'ing) Maltego throws this error.

In the case of iTDS, the trx in server mode returns a HTTP error code upon exceptions. Therefore, your transforms work there.

Can you try to check if you are writing anything else to standard output and possibly avoid it?

**Comment by cuckool** [comment]
@totakura Oh my bad, it was not clear to me that worked that way. Thank you for clarifying.

**Comment by totakura** [comment]
Alright; I'm closing this issue. If need be, please re-open.
